{% set name = "sourmash_plugin_branchwater" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d9fd10efa454badf7eb0678c598817ab075856161ad567f056f5e0f4c29367d

build:
  number: 1
  skip: true  # [win or py<310]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.1.0,<2                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }} >=1.65.0
    - posix                               # [win]
    - make                                # [unix]
    - cargo-bundle-licenses
    - libclang                            # [unix]
    - clangdev                            # [unix]
    - xz
  host:
    - python
    - maturin >=1.1.0,<2
    - pip
  run:
    - python
    - xz
    - sourmash-minimal >=4.8.5,<5
    - libstdcxx-ng                        # [linux]
    - libgcc-ng                           # [linux]
    # Due to rocksDB: https://conda-forge.org/docs/maintainer/knowledge_base.html#newer-c-features-with-old-sdk

test:
  imports:
    - sourmash_plugin_branchwater
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sourmash-bio/sourmash_plugin_branchwater
  summary: fast search and gather extensions for sourmash
  license: AGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ctb
    - bluegenes
